#ifndef CBORDERSTYLEH
#define CBORDERSTYLEH

enum EBORDERSTYLE //18.18.3 ST_BorderStyle (Border Line Styles)
{
EBORDERSTYLE_NONE,
EBORDERSTYLE_DASHDOT,
EBORDERSTYLE_DASHDOTDOT,
EBORDERSTYLE_DASHED,
EBORDERSTYLE_DOTTED,
EBORDERSTYLE_DOUBLE,
EBORDERSTYLE_HAIR,
EBORDERSTYLE_MEDIUM,
EBORDERSTYLE_MEDIUMDASHDOT,
EBORDERSTYLE_MEDIUMDASHDOTDOT,
EBORDERSTYLE_MEDIUMDASHED,
EBORDERSTYLE_SLANTDASHDOT,
EBORDERSTYLE_THINCK,
EBORDERSTYLE_THIN,
};

#endif
